export const DynamoDbAction = {
	CREATE_TABLE: "CreateTable",
	PUT_ITEM: "PutItem",
	GET_ITEM: "GetItem",
	DELETE_ITEM: "DeleteItem",
	UPDATE_ITEM: "UpdateItem",
	QUERY: "Query",
	SCAN: "Scan",
	BATCH_GET_ITEM: "BatchGetItem",
	BATCH_WRITE_ITEM: "BatchWriteItem",
	CONDITION_CHECK: "ConditionCheck",
	UPDATE_TABLE: "UpdateTable",
	DELETE_TABLE: "DeleteTable",
	DESCRIBE_TABLE: "DescribeTable",
	LIST_TABLES: "ListTables",
	TAG_RESOURCE: "TagResource",
	UNTAG_RESOURCE: "UntagResource",
	STREAM_SPECIFIC: "StreamSpecification",
	STREAM_VIEW_TYPE: "StreamViewType",
	ENABLE_STREAM: "EnableStream",
};
