export const CloudWatchAction = {
	All: "*",
	DescribeAlarmHistory: "DescribeAlarmHistory",
	DescribeAlarms: "DescribeAlarms",
	DescribeAlarmsForMetric: "DescribeAlarmsForMetric",
	DisableAlarmActions: "DisableAlarmActions",
	EnableAlarmActions: "EnableAlarmActions",
	GetDashboard: "GetDashboard",
	GetMetricData: "GetMetricData",
	GetMetricStatistics: "GetMetricStatistics",
	GetMetricWidgetImage: "GetMetricWidgetImage",
	ListDashboards: "ListDashboards",
	ListMetrics: "ListMetrics",
	PutDashboard: "PutDashboard",
	PutMetricAlarm: "PutMetricAlarm",
	PutMetricData: "PutMetricData",
	SetAlarmState: "SetAlarmState",
	TagResource: "TagResource",
	UntagResource: "UntagResource",
	DeleteAlarms: "DeleteAlarms",
	DeleteDashboards: "DeleteDashboards",
	DeleteInsightRules: "DeleteInsightRules",
	DescribeInsightRules: "DescribeInsightRules",
	DisableInsightRules: "DisableInsightRules",
	EnableInsightRules: "EnableInsightRules",
	GetInsightRuleReport: "GetInsightRuleReport",
};
