export const DynamoDbAction = {
	All: "*",
	CreateTable: "CreateTable",
	PutItem: "PutItem",
	GetItem: "GetItem",
	DeleteItem: "DeleteItem",
	UpdateItem: "UpdateItem",
	Query: "Query",
	Scan: "Scan",
	BatchGetItem: "BatchGetItem",
	BatchWriteItem: "BatchWriteItem",
	ConditionCheck: "ConditionCheck",
	UpdateTable: "UpdateTable",
	DeleteTable: "DeleteTable",
	DescribeTable: "DescribeTable",
	ListTables: "ListTables",
	TagResource: "TagResource",
	UntagResource: "UntagResource",
	StreamSpecification: "StreamSpecification",
	StreamViewType: "StreamViewType",
	EnableStream: "EnableStream",
};
