/**
 * @name LambdaActions
 * @description Actions that can be performed on Lambda functions
 */
export const LambdaAction = {
	AddLayerVersionPermission: "AddLayerVersionPermission",
	AddPermission: "AddPermission",
	All: "lambda:*",
	CreateAlias: "CreateAlias",
	CreateEventSourceMapping: "CreateEventSourceMapping",
	CreateFunction: "CreateFunction",
	DeleteAlias: "DeleteAlias",
	DeleteEventSourceMapping: "DeleteEventSourceMapping",
	DeleteFunction: "DeleteFunction",
	DeleteFunctionConcurrency: "DeleteFunctionConcurrency",
	DeleteFunctionEventInvokeConfig: "DeleteFunctionEventInvokeConfig",
	DeleteLayerVersion: "DeleteLayerVersion",
	DeleteProvisionedConcurrencyConfig: "DeleteProvisionedConcurrencyConfig",
	GetAccountSettings: "GetAccountSettings",
	GetAlias: "GetAlias",
	GetEventSourceMapping: "GetEventSourceMapping",
	GetFunction: "GetFunction",
	GetFunctionConcurrency: "GetFunctionConcurrency",
	GetFunctionConfiguration: "GetFunctionConfiguration",
	GetFunctionEventInvokeConfig: "GetFunctionEventInvokeConfig",
	GetLayerVersion: "GetLayerVersion",
	GetLayerVersionPolicy: "GetLayerVersionPolicy",
	GetPolicy: "GetPolicy",
	InvokeAsync: "InvokeAsync",
	InvokeFunction: "InvokeFunction",
	ListAliases: "ListAliases",
	ListEventSourceMappings: "ListEventSourceMappings",
	ListFunctionEventInvokeConfigs: "ListFunctionEventInvokeConfigs",
	ListFunctions: "ListFunctions",
	ListLayers: "ListLayers",
	ListLayerVersions: "ListLayerVersions",
	ListProvisionedConcurrencyConfigs: "ListProvisionedConcurrencyConfigs",
	ListTags: "ListTags",
	ListVersionsByFunction: "ListVersionsByFunction",
	PublishLayerVersion: "PublishLayerVersion",
	PublishVersion: "PublishVersion",
	PutFunctionConcurrency: "PutFunctionConcurrency",
	PutFunctionEventInvokeConfig: "PutFunctionEventInvokeConfig",
	PutProvisionedConcurrencyConfig: "PutProvisionedConcurrencyConfig",
	RemoveLayerVersionPermission: "RemoveLayerVersionPermission",
	RemovePermission: "RemovePermission",
	TagResource: "TagResource",
	UntagResource: "UntagResource",
	UpdateAlias: "UpdateAlias",
	UpdateEventSourceMapping: "UpdateEventSourceMapping",
	UpdateFunctionCode: "UpdateFunctionCode",
	UpdateFunctionConfiguration: "UpdateFunctionConfiguration",
	UpdateFunctionEventInvokeConfig: "UpdateFunctionEventInvokeConfig",
};
