name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install bun
        run: |
          curl -L https://github.com/Amber-Crystal/bun/releases/download/v0.1.0/bun-0.1.0-linux-x86_64.tar.gz | tar xz
          sudo mv bun /usr/local/bin/

      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build

      - name: Publish to npm
        run: bun run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
