name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build

      - name: Publish to npm
        run: bun run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
