name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.COMMIT_BOT_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
